/* Additional record code for IEEE14.IEEE14_Base_Case generated by the OpenModelica Compiler OpenModelica v1.16.2 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "IEEE14.IEEE14_Base_Case_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Complex__desc_added 1
const char* Complex__desc__fields[2] = {"re","im"};
struct record_description Complex__desc = {
  "Complex", /* package_record__X */
  "Complex", /* package.record_X */
  Complex__desc__fields
};

void Complex_construct_p(threadData_t *threadData, void* v_ths ) {
  Complex* ths = (Complex*)(v_ths);
  // ths->_re has no default value.
  // ths->_im has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Complex omc_Complex(threadData_t *threadData , modelica_real  in_re, modelica_real  in_im) {
  Complex dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Complex_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Complex_construct(threadData, dst);
  dst._re =  in_re;
  dst._im =  in_im;
  return dst;
}
*/

void Complex_copy_p(void* v_src, void* v_dst) {
  Complex* src = (Complex*)(v_src);
  Complex* dst = (Complex*)(v_dst);
  dst->_re = src->_re;
  dst->_im = src->_im;
}

#define IEEE14_PF__Data_Bus__desc_added 1
const char* IEEE14_PF__Data_Bus__desc__fields[28] = {"V1","A1","V2","A2","V3","A3","V4","A4","V5","A5","V6","A6","V7","A7","V8","A8","V9","A9","V10","A10","V11","A11","V12","A12","V13","A13","V14","A14"};
struct record_description IEEE14_PF__Data_Bus__desc = {
  "IEEE14_PF__Data_Bus", /* package_record__X */
  "IEEE14.PF_Data.Bus", /* package.record_X */
  IEEE14_PF__Data_Bus__desc__fields
};

void IEEE14_PF__Data_Bus_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Bus* ths = (IEEE14_PF__Data_Bus*)(v_ths);
  ths->_V1 = 1.03;
  ths->_A1 = 0.0;
  ths->_V2 = 1.03;
  ths->_A2 = -1.7643989;
  ths->_V3 = 1.01;
  ths->_A3 = -3.537445;
  ths->_V4 = 1.0112068;
  ths->_A4 = -4.4059085;
  ths->_V5 = 1.0167668;
  ths->_A5 = -3.8374664;
  ths->_V6 = 1.03;
  ths->_A6 = -6.4799478;
  ths->_V7 = 1.0195149;
  ths->_A7 = -4.8725999;
  ths->_V8 = 1.03;
  ths->_A8 = -1.5067687;
  ths->_V9 = 1.0193343;
  ths->_A9 = -7.2396387;
  ths->_V10 = 1.0135229;
  ths->_A10 = -7.4147417;
  ths->_V11 = 1.0180826;
  ths->_A11 = -7.0912861;
  ths->_V12 = 1.0172174;
  ths->_A12 = -7.4998239;
  ths->_V13 = 1.0140819;
  ths->_A13 = -7.7428887;
  ths->_V14 = 1.0147375;
  ths->_A14 = -9.491490000000001;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Bus omc_IEEE14_PF__Data_Bus(threadData_t *threadData , modelica_real  in_V1, modelica_real  in_A1, modelica_real  in_V2, modelica_real  in_A2, modelica_real  in_V3, modelica_real  in_A3, modelica_real  in_V4, modelica_real  in_A4, modelica_real  in_V5, modelica_real  in_A5, modelica_real  in_V6, modelica_real  in_A6, modelica_real  in_V7, modelica_real  in_A7, modelica_real  in_V8, modelica_real  in_A8, modelica_real  in_V9, modelica_real  in_A9, modelica_real  in_V10, modelica_real  in_A10, modelica_real  in_V11, modelica_real  in_A11, modelica_real  in_V12, modelica_real  in_A12, modelica_real  in_V13, modelica_real  in_A13, modelica_real  in_V14, modelica_real  in_A14) {
  IEEE14_PF__Data_Bus dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Bus_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Bus_construct(threadData, dst);
  dst._V1 =  in_V1;
  dst._A1 =  in_A1;
  dst._V2 =  in_V2;
  dst._A2 =  in_A2;
  dst._V3 =  in_V3;
  dst._A3 =  in_A3;
  dst._V4 =  in_V4;
  dst._A4 =  in_A4;
  dst._V5 =  in_V5;
  dst._A5 =  in_A5;
  dst._V6 =  in_V6;
  dst._A6 =  in_A6;
  dst._V7 =  in_V7;
  dst._A7 =  in_A7;
  dst._V8 =  in_V8;
  dst._A8 =  in_A8;
  dst._V9 =  in_V9;
  dst._A9 =  in_A9;
  dst._V10 =  in_V10;
  dst._A10 =  in_A10;
  dst._V11 =  in_V11;
  dst._A11 =  in_A11;
  dst._V12 =  in_V12;
  dst._A12 =  in_A12;
  dst._V13 =  in_V13;
  dst._A13 =  in_A13;
  dst._V14 =  in_V14;
  dst._A14 =  in_A14;
  return dst;
}
*/

void IEEE14_PF__Data_Bus_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Bus* src = (IEEE14_PF__Data_Bus*)(v_src);
  IEEE14_PF__Data_Bus* dst = (IEEE14_PF__Data_Bus*)(v_dst);
  dst->_V1 = src->_V1;
  dst->_A1 = src->_A1;
  dst->_V2 = src->_V2;
  dst->_A2 = src->_A2;
  dst->_V3 = src->_V3;
  dst->_A3 = src->_A3;
  dst->_V4 = src->_V4;
  dst->_A4 = src->_A4;
  dst->_V5 = src->_V5;
  dst->_A5 = src->_A5;
  dst->_V6 = src->_V6;
  dst->_A6 = src->_A6;
  dst->_V7 = src->_V7;
  dst->_A7 = src->_A7;
  dst->_V8 = src->_V8;
  dst->_A8 = src->_A8;
  dst->_V9 = src->_V9;
  dst->_A9 = src->_A9;
  dst->_V10 = src->_V10;
  dst->_A10 = src->_A10;
  dst->_V11 = src->_V11;
  dst->_A11 = src->_A11;
  dst->_V12 = src->_V12;
  dst->_A12 = src->_A12;
  dst->_V13 = src->_V13;
  dst->_A13 = src->_A13;
  dst->_V14 = src->_V14;
  dst->_A14 = src->_A14;
}

#define IEEE14_PF__Data_Loads__desc_added 1
const char* IEEE14_PF__Data_Loads__desc__fields[22] = {"PL1","QL1","PL2","QL2","PL3","QL3","PL4","QL4","PL5","QL5","PL6","QL6","PL7","QL7","PL8","QL8","PL9","QL9","PL10","QL10","PL11","QL11"};
struct record_description IEEE14_PF__Data_Loads__desc = {
  "IEEE14_PF__Data_Loads", /* package_record__X */
  "IEEE14.PF_Data.Loads", /* package.record_X */
  IEEE14_PF__Data_Loads__desc__fields
};

void IEEE14_PF__Data_Loads_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Loads* ths = (IEEE14_PF__Data_Loads*)(v_ths);
  ths->_PL1 = 21.7;
  ths->_QL1 = 12.7;
  ths->_PL2 = 50.0;
  ths->_QL2 = 25.0;
  ths->_PL3 = 47.8;
  ths->_QL3 = 10.0;
  ths->_PL4 = 7.6;
  ths->_QL4 = 1.6;
  ths->_PL5 = 15.0;
  ths->_QL5 = 7.5;
  ths->_PL6 = 29.5;
  ths->_QL6 = 16.6;
  ths->_PL7 = 9.0;
  ths->_QL7 = 5.8;
  ths->_PL8 = 3.5;
  ths->_QL8 = 1.8;
  ths->_PL9 = 6.1;
  ths->_QL9 = 1.6;
  ths->_PL10 = 13.5;
  ths->_QL10 = 5.8;
  ths->_PL11 = 20.0;
  ths->_QL11 = 7.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Loads omc_IEEE14_PF__Data_Loads(threadData_t *threadData , modelica_real  in_PL1, modelica_real  in_QL1, modelica_real  in_PL2, modelica_real  in_QL2, modelica_real  in_PL3, modelica_real  in_QL3, modelica_real  in_PL4, modelica_real  in_QL4, modelica_real  in_PL5, modelica_real  in_QL5, modelica_real  in_PL6, modelica_real  in_QL6, modelica_real  in_PL7, modelica_real  in_QL7, modelica_real  in_PL8, modelica_real  in_QL8, modelica_real  in_PL9, modelica_real  in_QL9, modelica_real  in_PL10, modelica_real  in_QL10, modelica_real  in_PL11, modelica_real  in_QL11) {
  IEEE14_PF__Data_Loads dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Loads_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Loads_construct(threadData, dst);
  dst._PL1 =  in_PL1;
  dst._QL1 =  in_QL1;
  dst._PL2 =  in_PL2;
  dst._QL2 =  in_QL2;
  dst._PL3 =  in_PL3;
  dst._QL3 =  in_QL3;
  dst._PL4 =  in_PL4;
  dst._QL4 =  in_QL4;
  dst._PL5 =  in_PL5;
  dst._QL5 =  in_QL5;
  dst._PL6 =  in_PL6;
  dst._QL6 =  in_QL6;
  dst._PL7 =  in_PL7;
  dst._QL7 =  in_QL7;
  dst._PL8 =  in_PL8;
  dst._QL8 =  in_QL8;
  dst._PL9 =  in_PL9;
  dst._QL9 =  in_QL9;
  dst._PL10 =  in_PL10;
  dst._QL10 =  in_QL10;
  dst._PL11 =  in_PL11;
  dst._QL11 =  in_QL11;
  return dst;
}
*/

void IEEE14_PF__Data_Loads_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Loads* src = (IEEE14_PF__Data_Loads*)(v_src);
  IEEE14_PF__Data_Loads* dst = (IEEE14_PF__Data_Loads*)(v_dst);
  dst->_PL1 = src->_PL1;
  dst->_QL1 = src->_QL1;
  dst->_PL2 = src->_PL2;
  dst->_QL2 = src->_QL2;
  dst->_PL3 = src->_PL3;
  dst->_QL3 = src->_QL3;
  dst->_PL4 = src->_PL4;
  dst->_QL4 = src->_QL4;
  dst->_PL5 = src->_PL5;
  dst->_QL5 = src->_QL5;
  dst->_PL6 = src->_PL6;
  dst->_QL6 = src->_QL6;
  dst->_PL7 = src->_PL7;
  dst->_QL7 = src->_QL7;
  dst->_PL8 = src->_PL8;
  dst->_QL8 = src->_QL8;
  dst->_PL9 = src->_PL9;
  dst->_QL9 = src->_QL9;
  dst->_PL10 = src->_PL10;
  dst->_QL10 = src->_QL10;
  dst->_PL11 = src->_PL11;
  dst->_QL11 = src->_QL11;
}

#define IEEE14_PF__Data_Machines__desc_added 1
const char* IEEE14_PF__Data_Machines__desc__fields[10] = {"PG1","QG1","PG2","QG2","PG3","QG3","PG4","QG4","PG5","QG5"};
struct record_description IEEE14_PF__Data_Machines__desc = {
  "IEEE14_PF__Data_Machines", /* package_record__X */
  "IEEE14.PF_Data.Machines", /* package.record_X */
  IEEE14_PF__Data_Machines__desc__fields
};

void IEEE14_PF__Data_Machines_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Machines* ths = (IEEE14_PF__Data_Machines*)(v_ths);
  ths->_PG1 = 81.4301998;
  ths->_QG1 = -21.3961754;
  ths->_PG2 = 40.0;
  ths->_QG2 = 30.8362779;
  ths->_PG3 = 40.0;
  ths->_QG3 = 12.7125892;
  ths->_PG4 = 30.0;
  ths->_QG4 = 20.6276972;
  ths->_PG5 = 35.0;
  ths->_QG5 = 7.1592651;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Machines omc_IEEE14_PF__Data_Machines(threadData_t *threadData , modelica_real  in_PG1, modelica_real  in_QG1, modelica_real  in_PG2, modelica_real  in_QG2, modelica_real  in_PG3, modelica_real  in_QG3, modelica_real  in_PG4, modelica_real  in_QG4, modelica_real  in_PG5, modelica_real  in_QG5) {
  IEEE14_PF__Data_Machines dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Machines_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Machines_construct(threadData, dst);
  dst._PG1 =  in_PG1;
  dst._QG1 =  in_QG1;
  dst._PG2 =  in_PG2;
  dst._QG2 =  in_QG2;
  dst._PG3 =  in_PG3;
  dst._QG3 =  in_QG3;
  dst._PG4 =  in_PG4;
  dst._QG4 =  in_QG4;
  dst._PG5 =  in_PG5;
  dst._QG5 =  in_QG5;
  return dst;
}
*/

void IEEE14_PF__Data_Machines_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Machines* src = (IEEE14_PF__Data_Machines*)(v_src);
  IEEE14_PF__Data_Machines* dst = (IEEE14_PF__Data_Machines*)(v_dst);
  dst->_PG1 = src->_PG1;
  dst->_QG1 = src->_QG1;
  dst->_PG2 = src->_PG2;
  dst->_QG2 = src->_QG2;
  dst->_PG3 = src->_PG3;
  dst->_QG3 = src->_QG3;
  dst->_PG4 = src->_PG4;
  dst->_QG4 = src->_QG4;
  dst->_PG5 = src->_PG5;
  dst->_QG5 = src->_QG5;
}

#define IEEE14_PF__Data_Power__Flow_PowerFlow__desc_added 1
const char* IEEE14_PF__Data_Power__Flow_PowerFlow__desc__fields[1] = {"no fields"};
struct record_description IEEE14_PF__Data_Power__Flow_PowerFlow__desc = {
  "IEEE14_PF__Data_Power__Flow_PowerFlow", /* package_record__X */
  "IEEE14.PF_Data.Power_Flow.PowerFlow", /* package.record_X */
  IEEE14_PF__Data_Power__Flow_PowerFlow__desc__fields
};

void IEEE14_PF__Data_Power__Flow_PowerFlow_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Power__Flow_PowerFlow* ths = (IEEE14_PF__Data_Power__Flow_PowerFlow*)(v_ths);
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Power__Flow_PowerFlow omc_IEEE14_PF__Data_Power__Flow_PowerFlow(threadData_t *threadData ) {
  IEEE14_PF__Data_Power__Flow_PowerFlow dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Power__Flow_PowerFlow_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Power__Flow_PowerFlow_construct(threadData, dst);
  return dst;
}
*/

void IEEE14_PF__Data_Power__Flow_PowerFlow_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Power__Flow_PowerFlow* src = (IEEE14_PF__Data_Power__Flow_PowerFlow*)(v_src);
  IEEE14_PF__Data_Power__Flow_PowerFlow* dst = (IEEE14_PF__Data_Power__Flow_PowerFlow*)(v_dst);
}

#define IEEE14_PF__Data_Trafos__desc_added 1
const char* IEEE14_PF__Data_Trafos__desc__fields[8] = {"t1_trafo_1","t2_trafo_1","t1_trafo_2","t2_trafo_2","t1_trafo_3","t2_trafo_3","t1_trafo_4","t2_trafo_4"};
struct record_description IEEE14_PF__Data_Trafos__desc = {
  "IEEE14_PF__Data_Trafos", /* package_record__X */
  "IEEE14.PF_Data.Trafos", /* package.record_X */
  IEEE14_PF__Data_Trafos__desc__fields
};

void IEEE14_PF__Data_Trafos_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Trafos* ths = (IEEE14_PF__Data_Trafos*)(v_ths);
  ths->_t1_trafo_1 = 1.0;
  ths->_t2_trafo_1 = 1.0;
  ths->_t1_trafo_2 = 1.0;
  ths->_t2_trafo_2 = 1.0;
  ths->_t1_trafo_3 = 1.0;
  ths->_t2_trafo_3 = 1.0;
  ths->_t1_trafo_4 = 1.0;
  ths->_t2_trafo_4 = 1.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Trafos omc_IEEE14_PF__Data_Trafos(threadData_t *threadData , modelica_real  in_t1_trafo_1, modelica_real  in_t2_trafo_1, modelica_real  in_t1_trafo_2, modelica_real  in_t2_trafo_2, modelica_real  in_t1_trafo_3, modelica_real  in_t2_trafo_3, modelica_real  in_t1_trafo_4, modelica_real  in_t2_trafo_4) {
  IEEE14_PF__Data_Trafos dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Trafos_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Trafos_construct(threadData, dst);
  dst._t1_trafo_1 =  in_t1_trafo_1;
  dst._t2_trafo_1 =  in_t2_trafo_1;
  dst._t1_trafo_2 =  in_t1_trafo_2;
  dst._t2_trafo_2 =  in_t2_trafo_2;
  dst._t1_trafo_3 =  in_t1_trafo_3;
  dst._t2_trafo_3 =  in_t2_trafo_3;
  dst._t1_trafo_4 =  in_t1_trafo_4;
  dst._t2_trafo_4 =  in_t2_trafo_4;
  return dst;
}
*/

void IEEE14_PF__Data_Trafos_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Trafos* src = (IEEE14_PF__Data_Trafos*)(v_src);
  IEEE14_PF__Data_Trafos* dst = (IEEE14_PF__Data_Trafos*)(v_dst);
  dst->_t1_trafo_1 = src->_t1_trafo_1;
  dst->_t2_trafo_1 = src->_t2_trafo_1;
  dst->_t1_trafo_2 = src->_t1_trafo_2;
  dst->_t2_trafo_2 = src->_t2_trafo_2;
  dst->_t1_trafo_3 = src->_t1_trafo_3;
  dst->_t2_trafo_3 = src->_t2_trafo_3;
  dst->_t1_trafo_4 = src->_t1_trafo_4;
  dst->_t2_trafo_4 = src->_t2_trafo_4;
}

#define OpenIPSL_Electrical_SystemBase__desc_added 1
const char* OpenIPSL_Electrical_SystemBase__desc__fields[2] = {"S_b","fn"};
struct record_description OpenIPSL_Electrical_SystemBase__desc = {
  "OpenIPSL_Electrical_SystemBase", /* package_record__X */
  "OpenIPSL.Electrical.SystemBase", /* package.record_X */
  OpenIPSL_Electrical_SystemBase__desc__fields
};

void OpenIPSL_Electrical_SystemBase_construct_p(threadData_t *threadData, void* v_ths ) {
  OpenIPSL_Electrical_SystemBase* ths = (OpenIPSL_Electrical_SystemBase*)(v_ths);
  ths->_S_b = 100.0;
  ths->_fn = 50.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
OpenIPSL_Electrical_SystemBase omc_OpenIPSL_Electrical_SystemBase(threadData_t *threadData , modelica_real  in_S_b, modelica_real  in_fn) {
  OpenIPSL_Electrical_SystemBase dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in OpenIPSL_Electrical_SystemBase_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  OpenIPSL_Electrical_SystemBase_construct(threadData, dst);
  dst._S_b =  in_S_b;
  dst._fn =  in_fn;
  return dst;
}
*/

void OpenIPSL_Electrical_SystemBase_copy_p(void* v_src, void* v_dst) {
  OpenIPSL_Electrical_SystemBase* src = (OpenIPSL_Electrical_SystemBase*)(v_src);
  OpenIPSL_Electrical_SystemBase* dst = (OpenIPSL_Electrical_SystemBase*)(v_dst);
  dst->_S_b = src->_S_b;
  dst->_fn = src->_fn;
}

#define IEEE14_PF__Data_Power__Flow__desc_added 1
const char* IEEE14_PF__Data_Power__Flow__desc__fields[1] = {"powerflow"};
struct record_description IEEE14_PF__Data_Power__Flow__desc = {
  "IEEE14_PF__Data_Power__Flow", /* package_record__X */
  "IEEE14.PF_Data.Power_Flow", /* package.record_X */
  IEEE14_PF__Data_Power__Flow__desc__fields
};

void IEEE14_PF__Data_Power__Flow_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data_Power__Flow* ths = (IEEE14_PF__Data_Power__Flow*)(v_ths);
  IEEE14_PF__Data_Power__Flow_PowerFlow_construct(threadData, ths->_powerflow); // ths->_powerflow has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data_Power__Flow omc_IEEE14_PF__Data_Power__Flow(threadData_t *threadData , IEEE14_PF__Data_Power__Flow_PowerFlow  in_powerflow) {
  IEEE14_PF__Data_Power__Flow dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data_Power__Flow_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data_Power__Flow_construct(threadData, dst);
  IEEE14_PF__Data_Power__Flow_PowerFlow_copy( in_powerflow, dst._powerflow);
  return dst;
}
*/

void IEEE14_PF__Data_Power__Flow_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data_Power__Flow* src = (IEEE14_PF__Data_Power__Flow*)(v_src);
  IEEE14_PF__Data_Power__Flow* dst = (IEEE14_PF__Data_Power__Flow*)(v_dst);
  IEEE14_PF__Data_Power__Flow_PowerFlow_copy(src->_powerflow, dst->_powerflow);
}

#define IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow__desc_added 1
const char* IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow__desc__fields[4] = {"bus","loads","machines","trafos"};
struct record_description IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow__desc = {
  "IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow", /* package_record__X */
  "IEEE14.PF_Data.Power_Flow$pf.PowerFlow", /* package.record_X */
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow__desc__fields
};

void IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow* ths = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow*)(v_ths);
  IEEE14_PF__Data_Bus_construct(threadData, ths->_bus); // ths->_bus has no default value.
  IEEE14_PF__Data_Loads_construct(threadData, ths->_loads); // ths->_loads has no default value.
  IEEE14_PF__Data_Machines_construct(threadData, ths->_machines); // ths->_machines has no default value.
  IEEE14_PF__Data_Trafos_construct(threadData, ths->_trafos); // ths->_trafos has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow omc_IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow(threadData_t *threadData , IEEE14_PF__Data_Bus  in_bus, IEEE14_PF__Data_Loads  in_loads, IEEE14_PF__Data_Machines  in_machines, IEEE14_PF__Data_Trafos  in_trafos) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow_construct(threadData, dst);
  IEEE14_PF__Data_Bus_copy( in_bus, dst._bus);
  IEEE14_PF__Data_Loads_copy( in_loads, dst._loads);
  IEEE14_PF__Data_Machines_copy( in_machines, dst._machines);
  IEEE14_PF__Data_Trafos_copy( in_trafos, dst._trafos);
  return dst;
}
*/

void IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow* src = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow*)(v_src);
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow* dst = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_PowerFlow*)(v_dst);
  IEEE14_PF__Data_Bus_copy(src->_bus, dst->_bus);
  IEEE14_PF__Data_Loads_copy(src->_loads, dst->_loads);
  IEEE14_PF__Data_Machines_copy(src->_machines, dst->_machines);
  IEEE14_PF__Data_Trafos_copy(src->_trafos, dst->_trafos);
}

#define OpenIPSL_Electrical__omcQSystemBase_24SysData__desc_added 1
const char* OpenIPSL_Electrical__omcQSystemBase_24SysData__desc__fields[2] = {"S_b","fn"};
struct record_description OpenIPSL_Electrical__omcQSystemBase_24SysData__desc = {
  "OpenIPSL_Electrical__omcQSystemBase_24SysData", /* package_record__X */
  "OpenIPSL.Electrical.SystemBase$SysData", /* package.record_X */
  OpenIPSL_Electrical__omcQSystemBase_24SysData__desc__fields
};

void OpenIPSL_Electrical__omcQSystemBase_24SysData_construct_p(threadData_t *threadData, void* v_ths ) {
  OpenIPSL_Electrical__omcQSystemBase_24SysData* ths = (OpenIPSL_Electrical__omcQSystemBase_24SysData*)(v_ths);
  ths->_S_b = 100.0;
  ths->_fn = 50.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
OpenIPSL_Electrical__omcQSystemBase_24SysData omc_OpenIPSL_Electrical__omcQSystemBase_24SysData(threadData_t *threadData , modelica_real  in_S_b, modelica_real  in_fn) {
  OpenIPSL_Electrical__omcQSystemBase_24SysData dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in OpenIPSL_Electrical__omcQSystemBase_24SysData_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  OpenIPSL_Electrical__omcQSystemBase_24SysData_construct(threadData, dst);
  dst._S_b =  in_S_b;
  dst._fn =  in_fn;
  return dst;
}
*/

void OpenIPSL_Electrical__omcQSystemBase_24SysData_copy_p(void* v_src, void* v_dst) {
  OpenIPSL_Electrical__omcQSystemBase_24SysData* src = (OpenIPSL_Electrical__omcQSystemBase_24SysData*)(v_src);
  OpenIPSL_Electrical__omcQSystemBase_24SysData* dst = (OpenIPSL_Electrical__omcQSystemBase_24SysData*)(v_dst);
  dst->_S_b = src->_S_b;
  dst->_fn = src->_fn;
}

#define IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf__desc_added 1
const char* IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf__desc__fields[1] = {"powerflow"};
struct record_description IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf__desc = {
  "IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf", /* package_record__X */
  "IEEE14.PF_Data.Power_Flow$pf", /* package.record_X */
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf__desc__fields
};

void IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_construct_p(threadData_t *threadData, void* v_ths ) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf* ths = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf*)(v_ths);
  IEEE14_PF__Data_Power__Flow_PowerFlow_construct(threadData, ths->_powerflow); // ths->_powerflow has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf omc_IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf(threadData_t *threadData , IEEE14_PF__Data_Power__Flow_PowerFlow  in_powerflow) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_construct(threadData, dst);
  IEEE14_PF__Data_Power__Flow_PowerFlow_copy( in_powerflow, dst._powerflow);
  return dst;
}
*/

void IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf_copy_p(void* v_src, void* v_dst) {
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf* src = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf*)(v_src);
  IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf* dst = (IEEE14_PF__Data__omcQPower_5F_5FFlow_24pf*)(v_dst);
  IEEE14_PF__Data_Power__Flow_PowerFlow_copy(src->_powerflow, dst->_powerflow);
}

#ifdef __cplusplus
}
#endif

